name: Build FW
on: push
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare system
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build PocketPico Firmware
        run: make configure build

      - name: Set Version Variable
        run: echo "FW_VERSION=${GITHUB_REF#refs/*/}" | sed -r 's,/,-,g' >> $GITHUB_ENV

      - name: Save PocketPico Firmware Binaries
        uses: actions/upload-artifact@v4
        with:
          name: PocketPico-${{ env.FW_VERSION }}
          path: |
            build/PocketPico.bin
            build/PocketPico.uf2
          if-no-files-found: error

  create-release:
    name: Create FW Release
    runs-on: ubuntu-latest
    needs: [build-firmware]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set Version Variable
        run: echo "FW_VERSION=${GITHUB_REF#refs/*/}" | sed -r 's,/,-,g' >> $GITHUB_ENV

      - name: Get production files for EDM4-A
        uses: actions/download-artifact@v4
        with:
          name: PocketPico-${{ env.FW_VERSION }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: PocketPico ${{ env.FW_VERSION }}
          draft: false
          fail_on_unmatched_files: true
          files: ./PocketPico.*
